### ISSUE TITLE
Solving errors related to building the website

### ISSUE THREAD

**Issue by hayoung0Lee** [facebook/yoga#1109]
I want to share how I successfully built the gatsby project inside the website folder.

## Problem
Hi, I was trying to build the project in the website folder to see how the playground of yoga official website works. Unfortunately, the gatsby project wasn't working as I really wished. I encountered errors related to yoga-layout.

I am currently using `M1 IMac` and my node version is `v14.17.3`. I tried multiple times to `yarn install` this project. But the error below happened. 
```
/Users/hayoung/Library/Caches/node-gyp/14.17.3/include/node/v8.h:4446:22: note: passing argument to parameter 'context' here
      Local<Context> context, FunctionCallback callback,
                     ^
In file included from ../sources/Config.cc:12:
In file included from ../sources/./Config.hh:12:
In file included from ../../nbind/include/nbind/api.h:71:
In file included from ../../nbind/include/nbind/v8/BindWrapper.h:55:
In file included from ../../nan/nan.h:203:
In file included from ../../nan/nan_new.h:189:
../../nan/nan_implementation_12_inl.h:337:37: error: too few arguments to function call, expected 2, have 1
  return v8::StringObject::New(value).As<v8::StringObject>();
         ~~~~~~~~~~~~~~~~~~~~~      ^
/Users/hayoung/Library/Caches/node-gyp/14.17.3/include/node/v8.h:5854:23: note: 'New' declared here
  static Local<Value> New(Isolate* isolate, Local<String> value);
                      ^
In file included from ../sources/Config.cc:12:
In file included from ../sources/./Config.hh:12:
In file included from ../../nbind/include/nbind/api.h:71:
In file included from ../../nbind/include/nbind/v8/BindWrapper.h:55:
../../nan/nan.h:1034:53: error: too few arguments to function call, single argument 'context' was not specified
      v8::Local<v8::String> string = from->ToString();
                                     ~~~~~~~~~~~~~~ ^
/Users/hayoung/Library/Caches/node-gyp/14.17.3/include/node/v8.h:2810:44: note: 'ToString' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<String> ToString(
                                           ^
In file included from ../sources/Config.cc:12:
In file included from ../sources/./Config.hh:12:
In file included from ../../nbind/include/nbind/api.h:71:
In file included from ../../nbind/include/nbind/v8/BindWrapper.h:55:
../../nan/nan.h:1034:29: error: no viable conversion from 'MaybeLocal<v8::String>' to 'v8::Local<v8::String>'
      v8::Local<v8::String> string = from->ToString();
                            ^        ~~~~~~~~~~~~~~~~
/Users/hayoung/Library/Caches/node-gyp/14.17.3/include/node/v8.h:190:7: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'MaybeLocal<v8::String>' to 'const v8::Local<v8::String> &' for 1st argument
class Local {
      ^
/Users/hayoung/Library/Caches/node-gyp/14.17.3/include/node/v8.h:190:7: note: candidate constructor (the implicit move constructor) not viable: no known conversion from 'MaybeLocal<v8::String>' to 'v8::Local<v8::String> &&' for 1st argument
/Users/hayoung/Library/Caches/node-gyp/14.17.3/include/node/v8.h:194:13: note: candidate template ignored: could not match 'Local' against 'MaybeLocal'
  V8_INLINE Local(Local<S> that)
            ^
/Users/hayoung/Library/Caches/node-gyp/14.17.3/include/node/v8.h:337:22: note: explicit constructor is not a candidate
  explicit V8_INLINE Local(T* that) : val_(that) {}
                     ^
In file included from ../sources/Config.cc:12:
In file included from ../sources/./Config.hh:12:
In file included from ../../nbind/include/nbind/api.h:71:
In file included from ../../nbind/include/nbind/v8/BindWrapper.h:55:
../../nan/nan.h:1044:37: error: cannot initialize a parameter of type 'v8::Isolate *' with an lvalue of type 'char *'
        length_ = string->WriteUtf8(str_, static_cast<int>(len), 0, flags);
                                    ^~~~
/Users/hayoung/Library/Caches/node-gyp/14.17.3/include/node/v8.h:3037:26: note: passing argument to parameter 'isolate' here
  int WriteUtf8(Isolate* isolate, char* buffer, int length = -1,
                         ^
In file included from ../sources/Config.cc:12:
In file included from ../sources/./Config.hh:12:
In file included from ../../nbind/include/nbind/api.h:71:
In file included from ../../nbind/include/nbind/v8/BindWrapper.h:55:
../../nan/nan.h:1818:28: error: no matching member function for call to 'Set'
    New(persistentHandle)->Set(New(key).ToLocalChecked(), value);
    ~~~~~~~~~~~~~~~~~~~~~~~^~~
/Users/hayoung/Library/Caches/node-gyp/14.17.3/include/node/v8.h:3670:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/hayoung/Library/Caches/node-gyp/14.17.3/include/node/v8.h:3673:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
In file included from ../sources/Config.cc:12:
In file included from ../sources/./Config.hh:12:
In file included from ../../nbind/include/nbind/api.h:71:
In file included from ../../nbind/include/nbind/v8/BindWrapper.h:55:
../../nan/nan.h:1824:28: error: no matching member function for call to 'Set'
    New(persistentHandle)->Set(key, value);
    ~~~~~~~~~~~~~~~~~~~~~~~^~~
/Users/hayoung/Library/Caches/node-gyp/14.17.3/include/node/v8.h:3670:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/hayoung/Library/Caches/node-gyp/14.17.3/include/node/v8.h:3673:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
In file included from ../sources/Config.cc:12:
In file included from ../sources/./Config.hh:12:
In file included from ../../nbind/include/nbind/api.h:71:
In file included from ../../nbind/include/nbind/v8/BindWrapper.h:55:
../../nan/nan.h:1830:28: error: no matching member function for call to 'Set'
    New(persistentHandle)->Set(index, value);
    ~~~~~~~~~~~~~~~~~~~~~~~^~~
/Users/hayoung/Library/Caches/node-gyp/14.17.3/include/node/v8.h:3670:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/hayoung/Library/Caches/node-gyp/14.17.3/include/node/v8.h:3673:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
In file included from ../sources/Config.cc:12:
In file included from ../sources/./Config.hh:12:
In file included from ../../nbind/include/nbind/api.h:71:
In file included from ../../nbind/include/nbind/v8/BindWrapper.h:55:
../../nan/nan.h:1836:32: error: no matching member function for call to 'Get'
        New(persistentHandle)->Get(New(key).ToLocalChecked()));
        ~~~~~~~~~~~~~~~~~~~~~~~^~~
/Users/hayoung/Library/Caches/node-gyp/14.17.3/include/node/v8.h:3717:43: note: candidate function not viable: requires 2 arguments, but 1 was provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
/Users/hayoung/Library/Caches/node-gyp/14.17.3/include/node/v8.h:3720:43: note: candidate function not viable: requires 2 arguments, but 1 was provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
In file included from ../sources/Config.cc:12:
In file included from ../sources/./Config.hh:12:
In file included from ../../nbind/include/nbind/api.h:71:
In file included from ../../nbind/include/nbind/v8/BindWrapper.h:55:
../../nan/nan.h:1842:48: error: no matching member function for call to 'Get'
    return scope.Escape(New(persistentHandle)->Get(key));
                        ~~~~~~~~~~~~~~~~~~~~~~~^~~
/Users/hayoung/Library/Caches/node-gyp/14.17.3/include/node/v8.h:3717:43: note: candidate function not viable: requires 2 arguments, but 1 was provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
/Users/hayoung/Library/Caches/node-gyp/14.17.3/include/node/v8.h:3720:43: note: candidate function not viable: requires 2 arguments, but 1 was provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
In file included from ../sources/Config.cc:12:
In file included from ../sources/./Config.hh:12:
In file included from ../../nbind/include/nbind/api.h:71:
In file included from ../../nbind/include/nbind/v8/BindWrapper.h:55:
../../nan/nan.h:1847:48: error: no matching member function for call to 'Get'
    return scope.Escape(New(persistentHandle)->Get(index));
                        ~~~~~~~~~~~~~~~~~~~~~~~^~~
/Users/hayoung/Library/Caches/node-gyp/14.17.3/include/node/v8.h:3717:43: note: candidate function not viable: requires 2 arguments, but 1 was provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
/Users/hayoung/Library/Caches/node-gyp/14.17.3/include/node/v8.h:3720:43: note: candidate function not viable: requires 2 arguments, but 1 was provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
In file included from ../sources/Config.cc:12:
In file included from ../sources/./Config.hh:12:
In file included from ../../nbind/include/nbind/api.h:71:
In file included from ../../nbind/include/nbind/v8/BindWrapper.h:55:
In file included from ../../nan/nan.h:2657:
../../nan/nan_object_wrap.h:24:25: error: no member named 'IsNearDeath' in 'Nan::Persistent<v8::Object>'
    assert(persistent().IsNearDeath());
           ~~~~~~~~~~~~ ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/assert.h:93:25: note: expanded from macro 'assert'
    (__builtin_expect(!(e), 0) ? __assert_rtn(__func__, __FILE__, __LINE__, #e) : (void)0)
                        ^
In file included from ../sources/Config.cc:12:
In file included from ../sources/./Config.hh:12:
In file included from ../../nbind/include/nbind/api.h:71:
In file included from ../../nbind/include/nbind/v8/BindWrapper.h:55:
In file included from ../../nan/nan.h:2657:
../../nan/nan_object_wrap.h:67:18: error: no member named 'MarkIndependent' in 'Nan::Persistent<v8::Object>'
    persistent().MarkIndependent();
    ~~~~~~~~~~~~ ^
../../nan/nan_object_wrap.h:124:26: error: no member named 'IsNearDeath' in 'Nan::Persistent<v8::Object>'
    assert(wrap->handle_.IsNearDeath());
           ~~~~~~~~~~~~~ ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/assert.h:93:25: note: expanded from macro 'assert'
    (__builtin_expect(!(e), 0) ? __assert_rtn(__func__, __FILE__, __LINE__, #e) : (void)0)
                        ^
In file included from ../sources/Config.cc:12:
In file included from ../sources/./Config.hh:12:
In file included from ../../nbind/include/nbind/api.h:71:
In file included from ../../nbind/include/nbind/v8/BindWrapper.h:55:
In file included from ../../nan/nan.h:2753:
../../nan/nan_typedarray_contents.h:34:43: warning: 'GetContents' is deprecated: Use GetBackingStore. See http://crbug.com/v8/9908. [-Wdeprecated-declarations]
      data   = static_cast<char*>(buffer->GetContents().Data()) + byte_offset;
                                          ^
/Users/hayoung/Library/Caches/node-gyp/14.17.3/include/node/v8.h:5272:3: note: 'GetContents' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use GetBackingStore. See http://crbug.com/v8/9908.")
  ^
/Users/hayoung/Library/Caches/node-gyp/14.17.3/include/node/v8config.h:402:39: note: expanded from macro 'V8_DEPRECATE_SOON'
# define V8_DEPRECATE_SOON(message) [[deprecated(message)]]
                                      ^
In file included from ../sources/Config.cc:12:
In file included from ../sources/./Config.hh:12:
In file included from ../../nbind/include/nbind/api.h:71:
../../nbind/include/nbind/v8/BindWrapper.h:216:63: error: too few arguments to function call, single argument 'context' was not specified
                auto flags = static_cast<TypeFlags>(nanArgs[1]->Uint32Value());
                                                    ~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/hayoung/Library/Caches/node-gyp/14.17.3/include/node/v8.h:2866:41: note: 'Uint32Value' declared here
  V8_WARN_UNUSED_RESULT Maybe<uint32_t> Uint32Value(
                                        ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
1 warning and 20 errors generated.
make: *** [Release/obj.target/nbind/sources/Config.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/hayoung/.nvm/versions/node/v14.17.3/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:375:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Darwin 20.6.0
gyp ERR! command "/Users/hayoung/.nvm/versions/node/v14.17.3/bin/node" "/Users/hayoung/.nvm/versions/node/v14.17.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /Users/hayoung/bgp/yoga/website/node_modules/yoga-layout
gyp ERR! node -v v14.17.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! yoga-layout@1.9.3 build:node: `npm run copy-sources && autogypi && node-gyp configure build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the yoga-layout@1.9.3 build:node script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/hayoung/.npm/_logs/2021-10-27T01_23_53_242Z-debug.log
```

## My solution
I solved this by removing yoga-layout, but instead I used [yoga-layout-prebuilt](https://github.com/vadimdemedes/yoga-layout-prebuilt). 

![image](https://user-images.githubusercontent.com/70381940/138985839-d49680af-9119-426f-943c-8d4ffb549a55.png)

Now it works! I had to manually change several files but it now works like a charm. 
I don't know if it is the best way to handle this problem, but it works well enough for me to see how the playground is working. 

This is my repo: https://github.com/hayoung0Lee/yoga/tree/working-website

But I still don't get why there are types in js files? Any feedback is welcome!

**Comment by NickGerleman** [comment]
Thanks for sharing. Within the Yoga repo I added a resolution of nbind so that the website is installable using Node 12. It is a short term solution though, and there will need to be larger changes to how the JS bindings are handled. 

> But I still don't get why there are types in js files? Any feedback is welcome!
These types are for Flow instead of Typescript. Flow source files still use a ".JS" extension, but have "@flow" annotated in the source.
