### ISSUE TITLE
[NoSuchFieldError] --> mLayoutDirection 

### ISSUE THREAD

**Issue by crazy1235** [facebook/yoga#1148]
java.lang.NoSuchFieldError: no "I" field "mLayoutDirection" in class "Lk/e0/u2/j;" or its superclasses

**Comment by ihaoh** [comment]
@crazy1235 Did you solve this issue? I have similar error.

```java
java.lang.NoSuchFieldError: no "[F" field "arr" in class "Lo/AndroidMenu_androidKt;" or its superclasses

```

**Comment by NickGerleman** [comment]
Could you provide a callstack?

**Comment by ihaoh** [comment]
@NickGerleman Thank you for checking.

```
java.lang.NoSuchFieldError: no "[F" field "arr" in class "Lo/access$getBottomAppBarCutoutOffset$p;" or its superclasses
                                                                                                    	at com.facebook.yoga.YogaNative.jni_YGNodeCalculateLayoutJNI(Native Method)
                                                                                                    	at com.facebook.yoga.YogaNodeJNIBase.extraCallback(SourceFile:220)
                                                                                                    	at o.getHandlePosition-tuRUvjQ$foundation_release.calculateLayout(SourceFile:466)
                                                                                                    	at o.setValue$foundation_release.ICustomTabsCallback$Default(SourceFile:940)
                                                                                                    	at o.setValue$foundation_release.ICustomTabsCallback$Default(SourceFile:662)
                                                                                                    	at o.setValue$foundation_release.ICustomTabsCallback(SourceFile:623)
                                                                                                    	at com.facebook.react.uimanager.UIManagerModule$4.runGuarded(SourceFile:842)
                                                                                                    	at com.facebook.react.bridge.GuardedRunnable.run(SourceFile:30)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(SourceFile:27)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run
```

**Comment by NickGerleman** [comment]
Some of these methods, like `com.facebook.yoga.YogaNodeJNIBase.extraCallback` don't seem to exist (at least today, or in other GitHub searches).

But the other likely possibility is that `NoSuchFieldError` is being thrown by a Yoga measure function. Yoga layout may all into Java provided callbacks to provide measurements for leaf nodes (e.g. text). Yoga doesn't interact with anything akin to the class name mentioned here.

**Comment by riccardo-welld** [comment]
Same problem (after enabling dexguard / proguard):
```
Fatal Exception: java.lang.NoSuchFieldError: no "[F" field "arr" in class "Lcom/facebook/yoga/YogaNodeJNIFinalizer;" or its superclasses
       at com.facebook.yoga.YogaNative.jni_YGNodeCalculateLayoutJNI(YogaNative.java)
       at com.facebook.yoga.YogaNodeJNIBase.calculateLayout(YogaNodeJNIBase.java:220)
       at com.facebook.react.uimanager.ReactShadowNodeImpl.calculateLayout(ReactShadowNodeImpl.java:466)
       at com.facebook.react.uimanager.UIImplementation.calculateRootLayout(UIImplementation.java:940)
       at com.facebook.react.uimanager.UIImplementation.updateViewHierarchy(UIImplementation.java:662)
       at com.facebook.react.uimanager.UIImplementation.dispatchViewUpdates(UIImplementation.java:623)
       at com.facebook.react.uimanager.UIManagerModule$3.runGuarded(UIManagerModule.java:842)
       at com.facebook.react.bridge.GuardedRunnable.run(GuardedRunnable.java:30)
       at android.os.Handler.handleCallback(Handler.java:958)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
       at android.os.Looper.loopOnce(Looper.java:205)
       at android.os.Looper.loop(Looper.java:294)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
       at java.lang.Thread.run(Thread.java:1012)
```

**Comment by NickGerleman** [comment]
@riccardo-welld this looks like a different issue, and stemming from the React Native build.

I confirmed that, the field is annotated with `@DoNotStrip`, and that RN's proguard config is configured not to obfuscate based on the annotation (using the same rules we use, to ship Yoga with proguard inside of Meta). https://github.com/facebook/react-native/blob/489df722b3b9b4106d53d853d9ff6d0a3f177254/packages/react-native/ReactAndroid/proguard-rules.pro#L73

I supsect your configuration may not be correctly using provided proguard rules by React Native. If you are still seeing this, and are able to create a repro, consider making a new issue in RN repo.
