### ISSUE TITLE
JavaScript: setDisplay is not a function

### ISSUE THREAD

**Issue by lewispeel** [facebook/yoga#385]
Using setDisplay causes a TypeError.

```
// example code taken from
// https://github.com/facebook/yoga/blob/master/javascript/tests/Facebook.Yoga/YGDisplayTest.js

var root = Yoga.Node.create();

root.setFlexDirection(Yoga.FLEX_DIRECTION_ROW);
root.setWidth(100);
root.setHeight(100);

var root_child0 = Yoga.Node.create();
root_child0.setFlexGrow(1);
root.insertChild(root_child0, 0);

var root_child1 = Yoga.Node.create();
root_child1.setFlexGrow(1);
root_child1.setDisplay(Yoga.DISPLAY_NONE);
root.insertChild(root_child1, 1);
```

Produces this error;

```
C:\Users\peell\github\yoga\javascript\build\Release\nbind.js:1
(function (exports, require, module, __filename, __dirname) { ((function(root,wrapper){if(typeof define=="function"&&define.amd)define([],(function(){return wrapper}));else if(typeof module=="object"&&module.exports)module.exports=wrapper;else(root.nbind=root.nbind||{}).init=wrapper}))(this,(function(Module,cb){if(typeof Module=="function"){cb=Module;Module={}}Module.onRuntimeInitialized=(function(init,cb){return(function(){if(init)init.apply(this,arguments);try{Module.ccall("nbind_init")}catch(err){cb(err);return}cb(null,{bind:Module._nbind_value,reflect:Module.NBind.reflect,queryType:Module.NBind.queryType,toggleLightGC:Module.toggleLightGC,lib:Module})})})(Module.onRuntimeInitialized,cb);var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=fal
TypeError: root_child1.setDisplay is not a function
    at Object.<anonymous> (C:\Users\peell\gitlabs\yoga-test\build\main.js:14:13)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:456:3
```

**Comment by arcanis** [comment]
The (experimental) precompiled javascript bundle is currently out-of-date, and does not yet supports the `display` style and a few other features (note that they *are* supported in the Javascript version, but only if you build it yourself). We're in the process of streamlining the build workflow so that everything ends up being automated, but it will take some time.

**Comment by lewispeel** [comment]
I see. Thanks for clearing that up!
