### ISSUE TITLE
I cannot use YogaLayout in my project

### ISSUE THREAD

**Issue by kelciej** [facebook/yoga#503]
# Report

- [ ] I have searched [existing issues](https://github.com/facebook/yoga/issues) and this is not a duplicate

I did as https://facebook.github.io/yoga/docs/api/android/ says in my project.
gradle: 
compile 'com.facebook.yoga.android:yoga-layout:1.2.0'

Layout: 

<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:yoga="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <com.facebook.yoga.android.YogaLayout
        android:id="@+id/id_yogaLayout"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        yoga:align_items="center"
        yoga:flex_direction="row"
        yoga:padding_all="20dp">
    </com.facebook.yoga.android.YogaLayout>

</RelativeLayout>

MainActivity: 
public class YogaTest extends Activity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        LayoutInflater.from(this).setFactory(YogaViewLayoutFactory.getInstance());// Is it a must?
        super.onCreate(savedInstanceState);
        SoLoader.init(this, false);//Is it a must?
        setContentView(R.layout.activity_yoga_test);
    }
}

BUT there is always an exception like 

04-11 15:49:01.518 30658-30658/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.example.jiangjia.yogatest, PID: 30658
                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.jiangjia.yogatest/com.example.jiangjia.yogatest.MainActivity}: android.view.InflateException: Binary XML file line #8: Error inflating class com.facebook.yoga.android.YogaLayout
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2201)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2250)
                                                       at android.app.ActivityThread.access$900(ActivityThread.java:141)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1213)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:136)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5072)
                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
                                                       at dalvik.system.NativeStart.main(Native Method)
                                                    Caused by: android.view.InflateException: Binary XML file line #8: Error inflating class com.facebook.yoga.android.YogaLayout
                                                       at android.view.LayoutInflater.createView(LayoutInflater.java:623)
                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:699)
                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:400)
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
                                                       at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:290)
                                                       at android.app.Activity.setContentView(Activity.java:1947)
                                                       at com.example.jiangjia.yogatest.MainActivity.onCreate(MainActivity.java:17)
                                                       at android.app.Activity.performCreate(Activity.java:5249)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2165)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2250) 
                                                       at android.app.ActivityThread.access$900(ActivityThread.java:141) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1213) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:136) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5072) 
                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:515) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609) 
                                                       at dalvik.system.NativeStart.main(Native Method) 
                                                    Caused by: java.lang.reflect.InvocationTargetException
                                                       at java.lang.reflect.Constructor.constructNative(Native Method)
                                                       at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
                                                       at android.view.LayoutInflater.createView(LayoutInflater.java:597)
                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:699) 
                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:758) 
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:495) 
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:400) 
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
                                                       at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:290) 
                                                       at android.app.Activity.setContentView(Activity.java:1947) 
                                                       at com.example.jiangjia.yogatest.MainActivity.onCreate(MainActivity.java:17) 
                                                       at android.app.Activity.performCreate(Activity.java:5249) 
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2165) 
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2250) 
                                                       at android.app.ActivityThread.access$900(ActivityThread.java:141) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1213) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:136) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5072) 
                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:515) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609) 
                                                       at dalvik.system.NativeStart.main(Native Method) 
                                                    Caused by: java.lang.NoClassDefFoundError: com.facebook.soloader.SoLoader
                                                       at com.facebook.yoga.YogaNode.<clinit>(YogaNode.java:24)
                                                       at com.facebook.yoga.android.YogaLayout.<init>(YogaLayout.java:87)
                                                       at com.facebook.yoga.android.YogaLayout.<init>(YogaLayout.java:81)
                                                       at java.lang.reflect.Constructor.constructNative(Native Method) 
                                                       at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
                                                       at android.view.LayoutInflater.createView(LayoutInflater.java:597) 
                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:699) 
                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:758) 
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:495) 
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:400) 
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
                                                       at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:290) 
                                                       at android.app.Activity.setContentView(Activity.java:1947) 
                                                       at com.example.jiangjia.yogatest.MainActivity.onCreate(MainActivity.java:17) 
                                                       at android.app.Activity.performCreate(Activity.java:5249) 
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2165) 
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2250) 
                                                       at android.app.ActivityThread.access$900(ActivityThread.java:141) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1213) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:136) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5072) 
                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:515) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609) 
                                                       at dalvik.system.NativeStart.main(Native Method) 

I have no idea what went wrong! Please give me some more guide! 😂

**Comment by rspencer01** [comment]
Part of the problem may be that the documentation is outdated slightly.   I have fixed the gists that supply the sample code, but they aren't updating on the site (hoping that this is a cache issue).

First up, your XML should look like this:
```
<com.facebook.yoga.android.YogaLayout
    android:id="@+id/id_yogaLayout"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    yoga:yg_alignItems="center"
    yoga:yg_flexDirection="row"
    yoga:yg_paddingAll="20dp">
</com.facebook.yoga.android.YogaLayout>
```

Note the `yg_` prefixes.

Secondly if you include the first line with `// Is it a must?` you should be able to replace `<com.facebook.yoga.android.YogaLayout>` with `<YogaLayout>`.  Or you can leave it there and keep the longer tag.

Finally, yes, you do need the SoLoader line.

However, what I think is probably causing your issue at the moment is the lack of SoLoader in your binary  (the pertinent error is half way through that massive stack:
```
Caused by: java.lang.NoClassDefFoundError: com.facebook.soloader.SoLoader
at com.facebook.yoga.YogaNode.(YogaNode.java:24)
```

So make sure you add SoLoader into the dependencies of your project.  @emilsjolander can we make this happen automatically via the POMs?

**Comment by ztickm** [comment]
@rspencer01 Wouldn't it be better if the SoLoader line was executed in a custom Application class ?

**Comment by rspencer01** [comment]
I personally think extending the Application class simply to load SoLoader would be as, if not more confusing. Your also be exchanging "don't forget to initialize SoLoader" for "don't forget to use our custom application class" which feels more mysterious and unintuitive to me.  Besides, SoLoader might be useful for other native libraries, and you'd want to be explicit then.

**Comment by emilsjolander** [comment]
@rspencer01 I thought it was a automatic dependency. I'll look into it for the next release.

**Comment by rorlig** [comment]
link to android docs https://yogalayout.com/docs/api/android/ is broken. please update the link

**Comment by NickGerleman** [comment]
It looks like this issue is stale. Please reopen if you see the same behavior on the latest version of Yoga.
