### ISSUE TITLE
How to display in Android Preview

### ISSUE THREAD

**Issue by ken-bem** [facebook/yoga#577]
# Report

- [*] I have searched [existing issues](https://github.com/facebook/yoga/issues) and this is not a duplicate

# Issues and Steps to Reproduce
Im trying to display in Android Preview
im using Android Studio 3

# Expected Behavior
Display in the Android Layout Preview

# Actual Behavior
`
java.lang.NoClassDefFoundError: Could not initialize class com.facebook.yoga.YogaNode
	at com.facebook.yoga.android.YogaLayout.<init>(YogaLayout.java:88)
	at com.facebook.yoga.android.YogaLayout.<init>(YogaLayout.java:82)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.jetbrains.android.uipreview.ViewLoader.createNewInstance(ViewLoader.java:481)
	at org.jetbrains.android.uipreview.ViewLoader.loadClass(ViewLoader.java:264)
	at org.jetbrains.android.uipreview.ViewLoader.loadView(ViewLoader.java:222)
	at com.android.tools.idea.rendering.LayoutlibCallbackImpl.loadView(LayoutlibCallbackImpl.java:206)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:337)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:348)
	at android.view.BridgeInflater.createViewFromTag(BridgeInflater.java:248)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:733)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:334)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:382)
	at com.android.tools.idea.layoutlib.LayoutLibrary.createSession(LayoutLibrary.java:193)
	at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:591)
	at com.android.tools.idea.rendering.RenderTask.lambda$inflate$3(RenderTask.java:739)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

`

**Comment by juanpmarin** [comment]
Any update on this ?

**Comment by NickGerleman** [comment]
It looks like this issue is stale. Please reopen if you see the same behavior on the latest version of Yoga.
