### ISSUE TITLE
Buck cannot find clang in Windows.

### ISSUE THREAD

**Issue by michelgb** [facebook/yoga#680]
I need some help to discriminate if this is a buck issue or a yoga build issue (maybe there is a setting or variable somewhere i have to set). I am getting the following error while execution `buck targets`.

```
C:\Android\android-sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang doesn't exist
```

However I checked the file and permissions myself. The only different is this file in windows has the .exe extension.

```
[2017-12-06 09:37:04.701][error][command:null][tid:83][com.facebook.buck.cli.Main] Uncaught exception at top level
com.google.common.util.concurrent.ExecutionError: com.google.common.util.concurrent.ExecutionError: com.google.common.util.concurrent.ExecutionError: java.lang.AssertionError: C:\Android\android-sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang doesn't exist.

	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2216)

	at com.google.common.cache.LocalCache.get(LocalCache.java:4147)

	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4151)

	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5140)

	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5146)

	at com.facebook.buck.rules.AbstractKnownBuildRuleTypesProvider.get(AbstractKnownBuildRuleTypesProvider.java:67)

	at com.facebook.buck.rules.KnownBuildRuleTypesProvider.get(KnownBuildRuleTypesProvider.java:1)

	at com.facebook.buck.parser.PerBuildState.getAllTargetNodesJob(PerBuildState.java:181)

	at com.facebook.buck.parser.Parser.resolveTargetSpecs(Parser.java:511)

	at com.facebook.buck.parser.Parser.buildTargetGraphForTargetNodeSpecs(Parser.java:394)

	at com.facebook.buck.cli.TargetsCommand.buildTargetGraphAndTargets(TargetsCommand.java:545)

	at com.facebook.buck.cli.TargetsCommand.runWithExecutor(TargetsCommand.java:343)

	at com.facebook.buck.cli.TargetsCommand.runWithoutHelp(TargetsCommand.java:315)

	at com.facebook.buck.cli.AbstractCommand.run(AbstractCommand.java:231)

	at com.facebook.buck.cli.AbstractContainerCommand.run(AbstractContainerCommand.java:79)

	at com.facebook.buck.cli.Main.runMainWithExitCode(Main.java:1030)

	at com.facebook.buck.cli.Main.runMainThenExit(Main.java:376)

	at com.facebook.buck.cli.Main.nailMain(Main.java:1869)

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

	at java.lang.reflect.Method.invoke(Unknown Source)

	at com.martiansoftware.nailgun.NGSession.run(NGSession.java:329)

Caused by: com.google.common.util.concurrent.ExecutionError: com.google.common.util.concurrent.ExecutionError: java.lang.AssertionError: C:\Android\android-sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang doesn't exist.

	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2216)

	at com.google.common.cache.LocalCache.get(LocalCache.java:4147)

	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4151)

	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5140)

	at com.facebook.buck.toolchain.impl.DefaultToolchainProvider.getOrCreate(DefaultToolchainProvider.java:226)

	at com.facebook.buck.toolchain.impl.DefaultToolchainProvider.getByName(DefaultToolchainProvider.java:192)

	at com.facebook.buck.toolchain.BaseToolchainProvider.getByName(BaseToolchainProvider.java:24)

	at com.facebook.buck.rules.AbstractKnownBuildRuleTypes.createInstance(AbstractKnownBuildRuleTypes.java:197)

	at com.facebook.buck.rules.AbstractDefaultKnownBuildRuleTypesFactory.create(AbstractDefaultKnownBuildRuleTypesFactory.java:42)

	at com.facebook.buck.rules.DefaultKnownBuildRuleTypesFactory.create(DefaultKnownBuildRuleTypesFactory.java:1)

	at com.facebook.buck.rules.AbstractKnownBuildRuleTypesProvider$1.load(AbstractKnownBuildRuleTypesProvider.java:46)

	at com.facebook.buck.rules.AbstractKnownBuildRuleTypesProvider$1.load(AbstractKnownBuildRuleTypesProvider.java:1)

	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3708)

	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2416)

	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2299)

	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2212)

	... 22 more

Caused by: com.google.common.util.concurrent.ExecutionError: java.lang.AssertionError: C:\Android\android-sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang doesn't exist.

	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2216)

	at com.google.common.cache.LocalCache.get(LocalCache.java:4147)

	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4151)

	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5140)

	at com.facebook.buck.toolchain.impl.DefaultToolchainProvider.getOrCreate(DefaultToolchainProvider.java:226)

	at com.facebook.buck.toolchain.impl.DefaultToolchainProvider.getByName(DefaultToolchainProvider.java:192)

	at com.facebook.buck.toolchain.BaseToolchainProvider.getByName(BaseToolchainProvider.java:24)

	at com.facebook.buck.cxx.toolchain.CxxPlatformsProviderFactory.createToolchain(CxxPlatformsProviderFactory.java:46)

	at com.facebook.buck.toolchain.impl.DefaultToolchainProvider.createToolchain(DefaultToolchainProvider.java:245)

	at com.facebook.buck.toolchain.impl.DefaultToolchainProvider.access$1(DefaultToolchainProvider.java:237)

	at com.facebook.buck.toolchain.impl.DefaultToolchainProvider$1.load(DefaultToolchainProvider.java:147)

	at com.facebook.buck.toolchain.impl.DefaultToolchainProvider$1.load(DefaultToolchainProvider.java:1)

	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3708)

	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2416)

	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2299)

	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2212)

	... 37 more

Caused by: java.lang.AssertionError: C:\Android\android-sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang doesn't exist.

	at com.facebook.infer.annotation.Assertions.assertCondition(Assertions.java:72)

	at com.facebook.buck.android.NdkCxxPlatforms$NdkCxxToolchainPaths.processPathPattern(NdkCxxPlatforms.java:951)

	at com.facebook.buck.android.NdkCxxPlatforms$NdkCxxToolchainPaths.getToolPath(NdkCxxPlatforms.java:1049)

	at com.facebook.buck.android.NdkCxxPlatforms.getToolPath(NdkCxxPlatforms.java:578)

	at com.facebook.buck.android.NdkCxxPlatforms.getCTool(NdkCxxPlatforms.java:605)

	at com.facebook.buck.android.NdkCxxPlatforms.build(NdkCxxPlatforms.java:455)

	at com.facebook.buck.android.NdkCxxPlatforms.getPlatforms(NdkCxxPlatforms.java:305)

	at com.facebook.buck.android.NdkCxxPlatforms.getPlatforms(NdkCxxPlatforms.java:251)

	at com.facebook.buck.android.NdkCxxPlatforms.getPlatforms(NdkCxxPlatforms.java:228)

	at com.facebook.buck.android.toolchain.impl.NdkCxxPlatformsProviderFactory.getNdkCxxPlatforms(NdkCxxPlatformsProviderFactory.java:63)

	at com.facebook.buck.android.toolchain.impl.NdkCxxPlatformsProviderFactory.createToolchain(NdkCxxPlatformsProviderFactory.java:42)

	at com.facebook.buck.toolchain.impl.DefaultToolchainProvider.createToolchain(DefaultToolchainProvider.java:245)

	at com.facebook.buck.toolchain.impl.DefaultToolchainProvider.access$1(DefaultToolchainProvider.java:237)

	at com.facebook.buck.toolchain.impl.DefaultToolchainProvider$1.load(DefaultToolchainProvider.java:147)

	at com.facebook.buck.toolchain.impl.DefaultToolchainProvider$1.load(DefaultToolchainProvider.java:1)

	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3708)

	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2416)

	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2299)

	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2212)

	... 52 more
```

**Comment by rlbartle** [comment]
I had the same issue using Windows 7.  I made a copy of all of the executables in the directory and removed the .exe extension and it worked.

**Comment by NickGerleman** [comment]
It looks like this issue is stale. Please reopen if you see the same behavior on the latest version of Yoga.
