### ISSUE TITLE
Android Sample Crashes 

### ISSUE THREAD

**Issue by rorlig** [facebook/yoga#728]
# Report

- [ ] I have searched [existing issues](https://github.com/facebook/yoga/issues) and this is not a duplicate

# Issues and Steps to Reproduce
run  buck install -r android/sample

# Expected Behavior
Sample app should run. 

# Actual Behavior
sample app crashes 

```
03-10 14:47:36.018 6947-6947/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.facebook.samples.yoga, PID: 6947
                                                 java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/os/BuildCompat;
                                                     at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:196)
                                                     at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:181)
                                                     at android.support.v7.app.AppCompatActivity.getDelegate(AppCompatActivity.java:521)
                                                     at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:71)
                                                     at com.facebook.samples.yoga.MainActivity.onCreate(MainActivity.java:33)
                                                     at android.app.Activity.performCreate(Activity.java:6662)
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
                                                     at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:154)
                                                     at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
                                                  Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.os.BuildCompat" on path: DexPathList[[zip file "/data/app/com.facebook.samples.yoga-1/base.apk"],nativeLibraryDirectories=[/data/app/com.facebook.samples.yoga-1/lib/x86, /system/fake-libs, /data/app/com.facebook.samples.yoga-1/base.apk!/lib/x86, /system/lib, /vendor/lib]]
                                                     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                     at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:196) 
                                                     at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:181) 
                                                     at android.support.v7.app.AppCompatActivity.getDelegate(AppCompatActivity.java:521) 
                                                     at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:71) 
                                                     at com.facebook.samples.yoga.MainActivity.onCreate(MainActivity.java:33) 
                                                     at android.app.Activity.performCreate(Activity.java:6662) 
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118) 
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599) 
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707) 
                                                     at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:154) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:6077) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756) 
03-10 14:47:36.019 1586-2988/? W/ActivityManager:   Force finishing activity com.facebook.samples.yoga/.MainActivity
03-10 14:47:36.019 2127-6936/? I/Icing: Usage reports ok 0, Failed Usage reports 0, indexed 0, rejected 0, imm upload true
03-10 14:47:36.033 2002-2218/? D/EGL_emulation: eglMakeCurrent: 0xab8052a0: ver 2 0 (tinfo 0xab803220)
03-10 14:47:36.041 1662-1844/? D/EGL_emulation: eglMakeCurrent: 0xa6f29f60: ver 2 0 (tinfo 0xa6f3c520)
03-10 14:47:36.055 1662-1844/? D/EGL_emulation: eglMakeCurrent: 0xa6f29f60: ver 2 0 (tinfo 0xa6f3c520)
03-10 14:47:36.062 1662-1844/? D/EGL_emulation: eglMakeCurrent: 0xa6f29f60: ver 2 0 (tinfo 0xa6f3c520)
03-10 14:47:36.071 1662-1844/? D/EGL_emulation: eglMakeCurrent: 0xa6f29f60: ver 2 0 (tinfo 0xa6f3c520)
03-10 14:47:36.078 1662-1844/? D/EGL_emulation: eglMakeCurrent: 0xa6f29f60: ver 2 0 (tinfo 0xa6f3c520)
03-10 14:47:36.089 1662-1844/? D/EGL_emulation: eglMakeCurrent: 0xa6f29f60: ver 2 0 (tinfo 0xa6f3c520)
03-10 14:47:36.096 1662-1844/? D/EGL_emulation: eglMakeCurrent: 0xa6f29f60: ver 2 0 (tinfo 0xa6f3c520)
03-10 14:47:36.101 1662-1844/? D/EGL_emulation: eglMakeCurrent: 0xa6f29f60: ver 2 0 (tinfo 0xa6f3c520)
03-10 14:47:36.116 1662-1844/? D/EGL_emulation: eglMakeCurrent: 0xa6f29f60: ver 2 0 (tinfo 0xa6f3c520)
03-10 14:47:36.130 1662-1844/? D/EGL_emulation: eglMakeCurrent: 0xa6f29f60: ver 2 0 (tinfo 0xa6f3c520)
03-10 14:47:36.135 1662-1844/? D/EGL_emulation: eglMakeCurrent: 0xa6f29f60: ver 2 0 (tinfo 0xa6f3c520)
03-10 14:47:36.141 1586-4396/? I/OpenGLRenderer: Initialized EGL, version 1.4
03-10 14:47:36.141 1586-4396/? D/OpenGLRenderer: Swap behavior 1
03-10 14:47:36.143 1586-4396/? W/OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
03-10 14:47:36.143 1586-4396/? D/OpenGLRenderer: Swap behavior 0
03-10 14:47:36.148 2127-6936/? I/Icing: Usage reports ok 0, Failed Usage reports 0, indexed 0, rejected 0, imm upload false
03-10 14:47:36.152 1586-4396/? D/EGL_emulation: eglCreateContext: 0x92ec5440: maj 2 min 0 rcv 2
03-10 14:47:36.162 1662-1844/? D/EGL_emulation: eglMakeCurrent: 0xa6f29f60: ver 2 0 (tinfo 0xa6f3c520)
03-10 14:47:36.166 1586-4396/? D/EGL_emulation: eglMakeCurrent: 0x92ec5440: ver 2 0 (tinfo 0x91de3d60)
03-10 14:47:36.168 1662-1844/? D/EGL_emulation: eglMakeCurrent: 0xa6f29f60: ver 2 0 (tinfo 0xa6f3c520)
03-10 14:47:36.177 2127-6936/? I/Icing: Usage reports ok 0, Failed Usage reports 0, indexed 0, rejected 0, imm upload false
03-10 14:47:36.194 1586-4396/? D/EGL_emulation: eglMakeCurrent: 0x92ec5440: ver 2 0 (tinfo 0x91de3d60)
03-10 14:47:36.195 1662-1844/? D/EGL_emulation: eglMakeCurrent: 0xa6f29f60: ver 2 0 (tinfo 0xa6f3c520)
03-10 14:47:36.213 1662-1844/? D/EGL_emulation: eglMakeCurrent: 0xa6f29f60: ver 2 0 (tinfo 0xa6f3c520)
03-10 14:47:36.223 1662-1844/? D/EGL_emulation: eglMakeCurrent: 0xa6f29f60: ver 2 0 (tinfo 0xa6f3c520)
03-10 14:47:36.228 2127-2480/? I/Icing: IndexChimeraService.getServiceInterface callingPackage=com.google.android.gms componentName=AppsCorpus serviceId=32
03-10 14:47:36.233 2127-2515/? I/Icing: IndexChimeraService.getServiceInterface callingPackage=com.google.android.gms componentName=AppsCorpus serviceId=36
03-10 14:47:36.237 1662-1844/? D/EGL_emulation: eglMakeCurrent: 0xa6f29f60: ver 2 0 (tinfo 0xa6f3c520)
03-10 14:47:36.249 1662-1844/? D/EGL_emulation: eglMakeCurrent: 0xa6f29f60: ver 2 0 (tinfo 0xa6f3c520)
03-10 14:47:36.263 2127-6936/? I/Icing: Usage reports ok 0, Failed Usage reports 0, indexed 0, rejected 0, imm upload false
03-10 14:47:36.316 2127-6936/? I/Icing: Usage reports ok 0, Failed Usage reports 0, indexed 0, rejected 0, imm upload false
03-10 14:47:36.541 1586-1600/? W/ActivityManager: Activity pause timeout for ActivityRecord{582cfd4 u0 com.facebook.samples.yoga/.MainActivity t112 f}
03-10 14:47:36.556 1304-4595/? D/gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 2691072
03-10 14:47:36.564 1304-1304/? E/EGL_emulation: tid 1304: eglCreateSyncKHR(1901): error 0x3004 (EGL_BAD_ATTRIBUTE)
03-10 14:47:36.643 2002-2218/? D/EGL_emulation: eglMakeCurrent: 0xab8052a0: ver 2 0 (tinfo 0xab803220)
03-10 14:47:36.689 1662-1844/? D/EGL_emulation: eglMakeCurrent: 0xa6f29f60: ver 2 0 (tinfo 0xa6f3c520)
03-10 14:47:36.975 2127-2481/? I/Icing: Indexing 6DF4C22A5374ED2C5EF60A7D5D299FF250D12186 from com.google.android.googlequicksearchbox
03-10 14:47:37.005 1586-1607/? I/WindowManager: Destroying surface Surface(name=Starting com.facebook.samples.yoga) called by com.android.server.wm.WindowStateAnimator.destroySurface:2016 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:882 com.android.server.wm.WindowState.removeLocked:1456 com.android.server.wm.WindowManagerService.removeWindowInnerLocked:2484 com.android.server.wm.AppWindowToken.destroySurfaces:365 com.android.server.wm.WindowStateAnimator.finishExit:565 com.android.server.wm.AppWindowAnimator.stepAnimationLocked:427 com.android.server.wm.WindowAnimator.updateAppWindowsLocked:176 
03-10 14:47:37.042 1586-1607/? W/WindowManager: Failed looking up window
                                                java.lang.IllegalArgumentException: Requested window android.view.ViewRootImpl$W@234a735 does not exist
                                                    at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:9107)
                                                    at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:9098)
                                                    at com.android.server.wm.WindowManagerService.removeWindow(WindowManagerService.java:2302)
                                                    at com.android.server.wm.Session.remove(Session.java:202)
                                                    at android.view.ViewRootImpl.dispatchDetachedFromWindow(ViewRootImpl.java:3286)
                                                    at android.view.ViewRootImpl.doDie(ViewRootImpl.java:5881)
                                                    at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3622)
                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                    at android.os.Looper.loop(Looper.java:154)
                                                    at android.os.HandlerThread.run(HandlerThread.java:61)
                                                    at com.android.server.ServiceThread.run(ServiceThread.java:46)
03-10 14:47:37.072 2127-2481/? I/Icing: Indexing done 6DF4C22A5374ED2C5EF60A7D5D299FF250D12186
03-10 14:47:37.229 2127-2481/? I/Icing: Indexing 66BBEEEC9FE1EBD458DB2A4DC8C2560002237C76 from com.google.android.gms
03-10 14:47:37.251 2127-2481/? I/Icing: Indexing done 66BBEEEC9FE1EBD458DB2A4DC8C2560002237C76
03-10 14:47:37.360 2127-2481/? I/Icing: Indexing 66BBEEEC9FE1EBD458DB2A4DC8C2560002237C76 from com.google.android.gms
03-10 14:47:37.364 2127-2481/? I/Icing: Indexing done 66BBEEEC9FE1EBD458DB2A4DC8C2560002237C76
03-10 14:47:41.941 6808-6824/? W/Babel: bcq TOOK TOO LONG! (15041ms > 10000ms)
03-10 14:47:46.853 1586-1600/? W/ActivityManager: Activity destroy timeout for ActivityRecord{582cfd4 u0 com.facebook.samples.yoga/.MainActivity t112 f}
03-10 14:47:50.487 4303-4340/? W/Finsky: [210] com.google.android.finsky.FinskyApp.i(1468): No account configured on this device.
03-10 14:47:50.487 4303-4340/? I/Finsky: [210] com.google.android.finsky.c.e.run(1151): Replicating app states via AMAS.
03-10 14:47:50.550 4303-4340/? I/Finsky: [210] com.google.android.finsky.c.c.a(311): Completed 0 account content syncs with 0 successful.
03-10 14:47:50.550 4303-4303/? I/Finsky: [1] com.google.android.finsky.services.j.a(149): Installation state replication succeeded.
```

# Link to Code
***If you have some code that maintainers can clone/test for themselves, bugs can be resolved much faster. Please paste a link here.***

***When applicable, use this [fiddle](https://jsfiddle.net/emilsjolander/jckmwztt/) to post a web repro.***

**Comment by hkusb** [comment]
Has the problem been solved?

**Comment by gengjiawen** [comment]
I have add gradle support to android sample, you can try it: https://github.com/facebook/yoga/pull/886.

**Comment by hasretsariyer** [comment]
The sample application still crashes. :'(

**Comment by NickGerleman** [comment]
@cortinico recently validated the app runs when built using the current reference Gradle build. Though this app will be going away along with the YogaLayout ViewGroup after Yoga 2.0 (unit tests will be the sample for building against the core engine).
