### ISSUE TITLE
Has anyone successfully installed yoga in lambda?

### ISSUE THREAD

**Issue by dberringer** [facebook/yoga#763]
# Report
I'm trying to install yoga in a lambda function but it is failing to build(see error below).  Has anyone successfully installed and used yoga in an aws lambda function?  If so what steps did you follow?  Thanks.

# Issues and Steps to Reproduce
npm install yoga-layout

> yoga-layout@1.9.3 install /home/ec2-user/environment/Test/node_modules/yoga-layout
> npm run build:node

> yoga-layout@1.9.3 build:node /home/ec2-user/environment/Test/node_modules/yoga-layout
> npm run copy-sources && autogypi && node-gyp configure build

> yoga-layout@1.9.3 copy-sources /home/ec2-user/environment/Test/node_modules/yoga-layout
> ! npm -s run is-monolithic || (rsync -r --checksum --delete ../yoga/ sources/yoga/)

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
make: Entering directory `/home/ec2-user/environment/Test/node_modules/yoga-layout/build'
  COPY Release/obj.target/nbind/geni/symbols.txt
  CXX(target) Release/obj.target/nbind/sources/yoga/Utils.o
g++: error: unrecognized command line option ‘-std=c++14’
make: *** [Release/obj.target/nbind/sources/yoga/Utils.o] Error 1
make: Leaving directory `/home/ec2-user/environment/Test/node_modules/yoga-layout/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/ec2-user/.nvm/versions/node/v8.10.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.9.85-38.58.amzn1.x86_64
gyp ERR! command "/home/ec2-user/.nvm/versions/node/v8.10.0/bin/node" "/home/ec2-user/.nvm/versions/node/v8.10.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /home/ec2-user/environment/Test/node_modules/yoga-layout
gyp ERR! node -v v8.10.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! yoga-layout@1.9.3 build:node: `npm run copy-sources && autogypi && node-gyp configure build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the yoga-layout@1.9.3 build:node script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ec2-user/.npm/_logs/2018-05-02T16_37_03_667Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! yoga-layout@1.9.3 install: `npm run build:node`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the yoga-layout@1.9.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ec2-user/.npm/_logs/2018-05-02T16_37_03_929Z-debug.log

# Expected Behavior
successful install

# Actual Behavior
Install is failing

# Link to Code
N/A

**Comment by dberringer** [comment]
I have been able to compile yoga-layout using the NPM package with a newer version of GCC(7.3.0) but it doesn't seem to matter because it still relies on a newer version of libstdc++.so.6 which isn't available in the aws lambda environment and I don't see how I could make changes to the lambda environment so that my compiled yoga-layout will run. If anyone has any ideas on how to run yoga-layout in aws lambda it working would be much appreciated.

When I try to import yoga-layout I get the following error:
/var/lang/lib/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /var/task/node_modules/yoga-layout/build/Release/nbind.node)
