### ISSUE TITLE
Build error on Arch Linux

### ISSUE THREAD

**Issue by onlined** [facebook/yoga#810]
# Issues and Steps to Reproduce
The master branch (2e66f8d8283149439d4dd41de68d64718c263f9e) cannot be successfully built using `buck build //:yoga` on Arch Linux (gcc 8.2.1)

# Expected Behavior
Successful build with the command `buck build //:yoga`.

# Actual Behavior
The build fails with following output:
```
yoga/Yoga.cpp: In function ‘void YGZeroOutLayoutRecursivly(YGNodeRef)’:
yoga/Yoga.cpp:1854:51: error: ‘void* memset(void*, int, size_t)’ clearing an object of non-trivial type ‘struct YGLayout’; use assignment or value-initialization instead [-Werror=class-memaccess]
   memset(&(node->getLayout()), 0, sizeof(YGLayout));
                                                   ^
In file included from yoga/YGNode.h:11,
                 from yoga/Utils.h:9,
                 from yoga/Yoga.cpp:13:
yoga/YGLayout.h:12:8: note: ‘struct YGLayout’ declared here
 struct YGLayout {
        ^~~~~~~~
cc1plus: all warnings being treated as errors
Build failed: Command failed with exit code 1.
stderr: yoga/Yoga.cpp: In function ‘void YGZeroOutLayoutRecursivly(YGNodeRef)’:
yoga/Yoga.cpp:1854:51: error: ‘void* memset(void*, int, size_t)’ clearing an object of non-trivial type ‘struct YGLayout’; use assignment or value-initialization instead [-Werror=class-memaccess]
   memset(&(node->getLayout()), 0, sizeof(YGLayout));
                                                   ^
In file included from yoga/YGNode.h:11,
                 from yoga/Utils.h:9,
                 from yoga/Yoga.cpp:13:
yoga/YGLayout.h:12:8: note: ‘struct YGLayout’ declared here
 struct YGLayout {
        ^~~~~~~~
cc1plus: all warnings being treated as errors
    When running <c++ preprocess_and_compile>.
    When building rule //:yoga#compile-Yoga.cpp.o9b5477b5,default.
Building: finished in 2.4 sec (100%) 10/10 jobs, 1 updated
  Total time: 2.4 sec
```

**Comment by onlined** [comment]
Thanks!

**Comment by arvsu** [comment]
I have tried to buck build //:yoga in windows 10. The build is getting failed. I have pasted the log below for reference.


_[2018-10-24 13:58:49.602][debug][command:eedc6329-687c-4c87-8973-09a67b8c6191][tid:96][com.facebook.buck.core.build.engine.impl.CachingBuildRuleBuilder] Building locally: //:yoga#compile-YGEnums.cpp.obj7fcea885,default
[2018-10-24 13:58:49.602][debug][command:eedc6329-687c-4c87-8973-09a67b8c6191][tid:94][com.facebook.buck.core.build.engine.impl.CachingBuildRuleBuilder] Building locally: //:yoga#compile-YGNodePrint.cpp.objdaa483bc,default
[2018-10-24 13:58:49.602][debug][command:eedc6329-687c-4c87-8973-09a67b8c6191][tid:96][com.facebook.buck.cxx.CxxPreprocessAndCompileStep] preprocess_and_compile yoga\YGEnums.cpp -> buck-out\gen\yoga#compile-YGEnums.cpp.obj7fcea885,default\out.obj
[2018-10-24 13:58:49.602][debug][command:eedc6329-687c-4c87-8973-09a67b8c6191][tid:96][com.facebook.buck.cxx.CxxPreprocessAndCompileStep] Running command (pwd=Optional[D:\yogaC++\yoga]): (verbosity level disables command output)
[2018-10-24 13:58:49.602][debug][command:eedc6329-687c-4c87-8973-09a67b8c6191][tid:95][com.facebook.buck.cxx.CxxPreprocessAndCompileStep] preprocess_and_compile yoga\YGNode.cpp -> buck-out\gen\yoga#compile-YGNode.cpp.obj24f5ec03,default\out.obj
[2018-10-24 13:58:49.602][debug][command:eedc6329-687c-4c87-8973-09a67b8c6191][tid:95][com.facebook.buck.cxx.CxxPreprocessAndCompileStep] Running command (pwd=Optional[D:\yogaC++\yoga]): (verbosity level disables command output)
[2018-10-24 13:58:49.618][debug][command:eedc6329-687c-4c87-8973-09a67b8c6191][tid:94][com.facebook.buck.cxx.CxxPreprocessAndCompileStep] preprocess_and_compile yoga\YGNodePrint.cpp -> buck-out\gen\yoga#compile-YGNodePrint.cpp.objdaa483bc,default\out.obj
[2018-10-24 13:58:49.618][debug][command:eedc6329-687c-4c87-8973-09a67b8c6191][tid:94][com.facebook.buck.cxx.CxxPreprocessAndCompileStep] Running command (pwd=Optional[D:\yogaC++\yoga]): (verbosity level disables command output)
[2018-10-24 13:58:49.618][debug][command:eedc6329-687c-4c87-8973-09a67b8c6191][tid:97][com.facebook.buck.cxx.CxxPreprocessAndCompileStep] preprocess_and_compile yoga\YGLayout.cpp -> buck-out\gen\yoga#compile-YGLayout.cpp.obj30798d53,default\out.obj
[2018-10-24 13:58:49.618][debug][command:eedc6329-687c-4c87-8973-09a67b8c6191][tid:97][com.facebook.buck.cxx.CxxPreprocessAndCompileStep] Running command (pwd=Optional[D:\yogaC++\yoga]): (verbosity level disables command output)
[2018-10-24 13:58:49.743][warn ][command:eedc6329-687c-4c87-8973-09a67b8c6191][tid:96][com.facebook.buck.cxx.CxxPreprocessAndCompileStep] error 2 preprocess_and_compile yoga\YGEnums.cpp
[2018-10-24 13:58:49.758][debug][command:eedc6329-687c-4c87-8973-09a67b8c6191][tid:96][com.facebook.buck.core.build.engine.impl.CachingBuildRuleBuilder] Building rule [//:yoga#compile-YGEnums.cpp.obj7fcea885,default] failed.
com.facebook.buck.step.StepFailedException: Command failed with exit code 2.
stderr: 
  When running <c++ preprocess_and_compile>.
	at com.facebook.buck.step.StepFailedException.createForFailingStepWithException(StepFailedException.java:57)
	at com.facebook.buck.step.StepFailedException.createForFailingStepWithExitCode(StepFailedException.java:51)
	at com.facebook.buck.step.DefaultStepRunner.runStepForBuildTarget(DefaultStepRunner.java:54)
	at com.facebook.buck.core.build.engine.impl.CachingBuildRuleBuilder$BuildRuleSteps.executeCommands(CachingBuildRuleBuilder.java:1362)
	at com.facebook.buck.core.build.engine.impl.CachingBuildRuleBuilder$BuildRuleSteps.executeCommandsNowThatDepsAreBuilt(CachingBuildRuleBuilder.java:1330)
	at com.facebook.buck.core.build.engine.impl.CachingBuildRuleBuilder$BuildRuleSteps.runWithExecutor(CachingBuildRuleBuilder.java:1289)
	at com.facebook.buck.core.build.engine.impl.CachingBuildRuleBuilder$BuildRuleSteps.run(CachingBuildRuleBuilder.java:1278)
	at com.facebook.buck.core.build.engine.impl.CachingBuildRuleBuilder$2.runWithDefaultExecutor(CachingBuildRuleBuilder.java:811)
	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.lambda$2(WeightedListeningExecutorService.java:100)
	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.lambda$0(WeightedListeningExecutorService.java:74)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:206)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:195)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:115)
	at com.google.common.util.concurrent.MoreExecutors$5$1.run(MoreExecutors.java:999)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: com.facebook.buck.core.exceptions.HumanReadableException: Command failed with exit code 2.
stderr: 
	at com.facebook.buck.step.StepFailedException.createForFailingStepWithExitCode(StepFailedException.java:52)
	... 15 more

[2018-10-24 13:58:49.790][warn ][command:eedc6329-687c-4c87-8973-09a67b8c6191][tid:97][com.facebook.buck.cxx.CxxPreprocessAndCompileStep] error 2 preprocess_and_compile yoga\YGLayout.cpp
[2018-10-24 13:58:49.790][debug][command:eedc6329-687c-4c87-8973-09a67b8c6191][tid:96][com.facebook.buck.core.build.engine.impl.CachingBuildRuleBuilder] Building rule [//:yoga#compile-YGLayout.cpp.obj30798d53,default] failed.
com.facebook.buck.step.StepFailedException: Command failed with exit code 2._

 I am not able to figure out what went wrong.
Can anybody help me out to resolve this build error? 

Thank You :-)
