### ISSUE TITLE
npm install error while installing

### ISSUE THREAD

**Issue by RakhmatovR** [facebook/yoga#811]
# Report

- [x] I have searched [existing issues](https://github.com/facebook/yoga/issues) and this is not a duplicate

# Issues and Steps to Reproduce
`npm install --save yoga-layout`

# Expected Behavior
Successful installation.

# Actual Behavior
```
> yoga-layout@1.9.3 install D:\...\node_modules\yoga-layout
> npm run build:node


> yoga-layout@1.9.3 build:node D:\...\node_modules\yoga-layout
> npm run copy-sources && autogypi && node-gyp configure build


> yoga-layout@1.9.3 copy-sources D:\...\node_modules\yoga-layout
> ! npm -s run is-monolithic || (rsync -r --checksum --delete ../yoga/ sources/yoga/)

'!' is not recognized as an internal or external command,
operable program or batch file.
'rsync' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! yoga-layout@1.9.3 copy-sources: `! npm -s run is-monolithic || (rsync -r --checksum --delete ../yoga/ sources/yoga/)`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the yoga-layout@1.9.3 copy-sources script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\rra.mcc\AppData\Roaming\npm-cache\_logs\2018-09-17T05_43_20_322Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! yoga-layout@1.9.3 build:node: `npm run copy-sources && autogypi && node-gyp configure build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the yoga-layout@1.9.3 build:node script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\rra.mcc\AppData\Roaming\npm-cache\_logs\2018-09-17T05_43_20_362Z-debug.log
npm WARN rollback Rolling back yoga-layout@1.9.3 failed (this is probably harmless): EBUSY: resource busy or locked, rmdir 'D:\...\node_modules\yoga-layout'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! yoga-layout@1.9.3 install: `npm run build:node`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the yoga-layout@1.9.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by RakhmatovR** [comment]
Here is the full log
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build:node' ]
2 info using npm@6.4.1
3 info using node@v10.10.0
4 verbose run-script [ 'prebuild:node', 'build:node', 'postbuild:node' ]
5 info lifecycle yoga-layout@1.9.3~prebuild:node: yoga-layout@1.9.3
6 info lifecycle yoga-layout@1.9.3~build:node: yoga-layout@1.9.3
7 verbose lifecycle yoga-layout@1.9.3~build:node: unsafe-perm in lifecycle true
8 verbose lifecycle yoga-layout@1.9.3~build:node: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\...\node_modules\yoga-layout\node_modules\.bin;D:\...\node_modules\.bin;C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\...\node_modules\yoga-layout\node_modules\.bin;D:\...\node_modules\.bin;C:\Users\rra.mcc\AppData\Roaming\cmder\vendor\conemu-maximus5\ConEmu\Scripts;C:\Users\rra.mcc\AppData\Roaming\cmder\vendor\conemu-maximus5;C:\Users\rra.mcc\AppData\Roaming\cmder\vendor\conemu-maximus5\ConEmu;C:\Program Files\Docker\Docker\Resources\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Users\rra.mcc\AppData\Roaming\cmder;C:\Program Files\Git\cmd;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\dotnet\;C:\Program Files\PostgreSQL\10\bin;;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\nodejs\;C:\Program Files\PuTTY\;C:\Program Files (x86)\Yarn\bin\;C:\Users\rra.mcc\.windows-build-tools\python27\;C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\rra.mcc\AppData\Roaming\npm\node_modules\windows-build-tools\node_modules\.bin;C:\Users\rra.mcc\AppData\Roaming\npm\node_modules\.bin;C:\Program Files\Docker\Docker\Resources\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Users\rra.mcc\AppData\Roaming\cmder;C:\Program Files\Git\cmd;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\dotnet\;C:\Program Files\PostgreSQL\10\bin;;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\nodejs\;C:\Users\rra.mcc\AppData\Local\Microsoft\WindowsApps;C:\Users\rra.mcc\.dotnet\tools;C:\Users\rra.mcc\AppData\Roaming\npm;C:\Users\rra.mcc\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\rra.mcc\AppData\Local\Yarn\bin
9 verbose lifecycle yoga-layout@1.9.3~build:node: CWD: D:\...\node_modules\yoga-layout
10 silly lifecycle yoga-layout@1.9.3~build:node: Args: [ '/d /s /c',
10 silly lifecycle   'npm run copy-sources && autogypi && node-gyp configure build' ]
11 silly lifecycle yoga-layout@1.9.3~build:node: Returned: code: 1  signal: null
12 info lifecycle yoga-layout@1.9.3~build:node: Failed to exec build:node script
13 verbose stack Error: yoga-layout@1.9.3 build:node: `npm run copy-sources && autogypi && node-gyp configure build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:962:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
14 verbose pkgid yoga-layout@1.9.3
15 verbose cwd D:\...\node_modules\yoga-layout
16 verbose Windows_NT 10.0.17134
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build:node"
18 verbose node v10.10.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error yoga-layout@1.9.3 build:node: `npm run copy-sources && autogypi && node-gyp configure build`
22 error Exit status 1
23 error Failed at the yoga-layout@1.9.3 build:node script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by RakhmatovR** [comment]
Duplicate https://github.com/facebook/yoga/issues/739
